#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 13:16:56 2020

@author: t1
"""
DNA_Reverse = {'A' : 'T' ,'T' : 'A','G' : 'C','C':'G'}

def reverse_dna(dna_seq):
    return ''.join([DNA_Reverse[l] for l in dna_seq[::-1]])

dna_seq = 'AGGACACACGCCACTGCAGTCGGGAAGTTCCATCCAGTGCGGGCGCCTGGGGCTTCCAACCGATAATTAAGAAGGTGTCATGGTGGGGCACTGGGCGTTATATAAATCGCTGCAAGCCTTCTACCGTAATCTTCCAATCAGATAGGTTAATAGTGGGTGAGCGCTCGACCAAAGACCCACCTGACTCAACATTGTACTTCGGTAAACTTATTTAGCACGTCGGCCCGAGCCGCGGAGTCTCGGACGCAGCCTTGTACTTTTGGCTGCCGGTCTCGGATATTTATACACAAAGGTCAGGGACAATACCCGCCATGTCACACTAACGTACTAAGAAGACTTAAGTTTACTAGAATCCAGTCGATTCTTCGAACGCAGATTGTATTAAGTAGGTGGGCGGGTTCAAACCAGGTATAGTGCTTCGGCCAAATACACCAGGGCAGTCTAAATCCCCACATCCAATGAACCGAAGTAACGTGTTCCGACTCGAGAATCTAAACAGCCGTACCCCAGTGTCATCAACGCTACGCGGAAAGCCATCGTCTATCGGCTGGGTGACCGTTCAAGATCTCCCTAGCGGATGCTCCGCCGGGGTGTGACAGCATATCTAAAAGTCGTCAACTCGCTCTAAGTAAGGGGGGCGCGAATGCGCCCGTAAGGGCCGACAGCGGGCGATTCCCATGGGTCTTTCTAGGAGCAAGCCCACCAGTATGGCACCGATCTACTTCAATTAGGTTATAGAGTCCGTCAACTCGGCCTTCAATCCGGTGCGAGTAGCGTCCATCACAGCCTTATCAAAATCAATGGTTGGTTCACCACGTCTTGGATATACGGACGCTATCTCTTCCAAACGACTCGGCCCTCTATCCGACCCACCGCATTCTGCGCAATATAGGTATCCAACATTGGGCACATG'
print(reverse_dna(dna_seq))