#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul  1 12:00:47 2020

@author: t1
"""
import collections

def count(dna_seq):
    if not dna_seq:
        raise Exception('invalid sequence')
        return None
    # res_dict = {'A':0,'T':0,'G':0,'C':0}
    # for nuc in dna_seq:
    #     res_dict[nuc] += 1
    # return res_dict
    return dict(collections.Counter(dna_seq))



dna_seq = 'GCTGGCCGCGAGGAGCTTATTAATCTTTCCTAGTATAGCAATGAGGGTTAAAGAGTGCCGGCACACGGAAAGGCCGTCCCACAGGACTCTATCGTACTAGATAGCGTTAGGATGACCCTAGCAGGCCTGTTCACCTGATGAATATACCAACTGCCAGAAAGGCAACGCCCAACTAATGTCGTTAACCTTGAAAAACCTGTATGATACCGTAGGCATATCAGGTAGCTGTAACCAACGTCTTCCCGATTGTTATAGAGTCCCACCTCTTGATTCTCCCAGCGGATAAGCGAGCCCAACCGTCCTGCGATATTGTAGTTAACGCCTTCTCGATGATAACCAGGTGAGAGCCCGAAGAGGATGTGCACTCGATCCACAACCGGGAGCAGGTGACCACGAAGATGTCCCATCACACAATGTAACAATCATCAAGCACCGACCCAAAGACGCGGCGCTATCTCGCGGGCCGCGCATTTGTGGCCATACTCCGAGGAGTGTTCGTCACCCTTGCATCCATCGGTGGTTGTAGATTGACCTACGTGTGTTTGGTTCATGCGCTAGCTTATTATATAACTCCCGCCCAGCATGGATAAAGGCGATTATCTAGCAAGCAGATCGTCCGCTTTAAGGTCCCAACTATTCTCCGGAAAGCCATCATAGCGTAAACAGTTGTTGATGAATTGGCCTCCTTGAAGCCTTGGCACATGCCAAGCTATCCGAGATTGTGCCGGGCGTCCAGCTGAAGTGCCAGACGCACAGACTCATTCACGAGAGGGCGCTAACCAGAAGGAGATTTGAACAGCTCTTAAATGTCGGCATCATCTCTG'
result = count(dna_seq)
print('{} {} {} {}'.format(result['A'],result['C'],result['G'],result['T']))