#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 20 12:17:08 2020

@author: t1
"""

def find_motif(seq,t):
    starts = []
    for i in range(len(seq)-len(t)):
        if t == seq[i : (i+len(t))]:
            starts.append(i+1)
    return starts
            
# seq = 'GATATATGCATATACTT'
# t = 'ATAT'

seq = 'AGCAACACTAGCAACAACACCGAGCAACAAACAGCAACATACAGGAGAGTAAGCAACAAGCAACAAGCAACACATGCAGCAACAGAGCAACAAGCAACATAGCAACACTAGCAACAGGGGTAGCAACAAGCAACAAGCAACATAGCAACAAGCTTAGCAACAAGCAACAACAGCAACATCAGAAGCAACAGAGCAACAAGCAACAGCCAGTTAGCAACAATCCGCAGCAACATAGCAACAGAGCAACATAATGTTAGCAACACCCTTAGCAACAAGCAACAGAGCAACAAGCAACAAATCAAGCAACATTCGAGCAACAACAGGGAGAGCAACAGACCGAGCAACACTAGCAACACCAGCAACACAGCAACACAGCAACATTGCTGCACAGCAACATACTCAGCAACAAAGCAACATGCAAAGAGCAACAGCAATTGGCCAGCAACAAGCAACAGTTCAAGAGCAACACGGAGCAACATAGCAACATCGGCCACTGTAGCAACAAAAGCAACAACAGCAACAAAGCAACACATGCGAGCAACAAGCAACAGAGCAACATAGCAACACAAGCAACAAGCAACAAGGGGGTCGCAAGCAACACCAGCAACACTATAGCAACAAGCAACAGCAGCAACAAGCAACAGAAGCAACACCGGTAGAGCAACATCAAAGCAACACAAGCAACACAGCAACACTAGCAACACAGCAACAAAGCAACAGTCATAGCCTAGCAACATAGCAACATTTAGCAACAAGCAACAGAGCAACATTAGCAACAAGAGCAACAAGCAACATATAGCAACATTAGCAACAGAGAGCAACAAAATGATAGCAACAAGCAACACTAGCAACAGAGCAACAGAGCAACACGAGCAACAAAAGCAACAAGCAACAAAGCAACAGCCAAGCAACAGCAGCAACAGCTAGCAACAAAAGCAACACGCGATAGCAACAAAGCAACAATAGCAACAGAA'
t = 'AGCAACAAG'

ans = find_motif(seq, t)

s = ''
for a in ans:
    s += str(a) + ' '
    
print(s)